### ISSUE TITLE
Feature selection process

### ISSUE THREAD

**Issue by armgilles** [Far0n/kaggle-homesite#1]
Hi @Far0n 

First i would like to thank you for sharing this script and congratulation for your Kaggle competition !

I try to reproduce the process of feature selection with your [xgbfi](https://github.com/Far0n/xgbfi).

As I understand the process : 
- 1) Fit a xgboost with original train file. I dump the model and I can analyse the feature importance with xgbfi.
- 2) Keep only the best feature (your `top111`) and find interaction between features (`interactions2way`, `interactions3way`...)
- 3) Reproduce process 1) and use CV to tune model, maybe add or delete some others features.

Is it the good way to go ?

I spent many hours and night to try it, but I don't find the same result at all. For example during the 1) process, I find `PropertyField37` very effective for 2 Interactions features. But it seems you didn't choose it. Can't understand why.

In the same case I have only 100 features used by xgboost. Some are present in your `top111` and some are missing. So much frustration ! 

If you are allowed to help me, you will save me some nights.

**Comment by Far0n** [comment]
The `top11` have not been found by using xgbfi alone. We used it together with a wrapper method,

**Comment by armgilles** [comment]
Ok @Faron thank for your reply. Have to go deeper so :)
